### ISSUE TITLE
Sugestões

### ISSUE THREAD

**Issue by brenoepics** [KoreaComK/visao-libertaria-site#109]
Olá, estive tentando rodar o site no meu localhost mas tive alguns problemas como desativar o captcha no localhost, os links dos scripts etc estão com link fixo no https e impossibilita de testar no localhost:xxxx e depois de migrar a db etc tive diversos problemas com o login retornando erros 500 ou fazia login mas minha sessão não era iniciada.. seria interessante tornar o site mais portável para atrair mais contribuidores.

**Comment by KoreaComK** [comment]
Para desativar o captcha, basta fazer um bypass no `verificaCaptcha` dentro do App/Controller/Site .

Os links com https são abertos da rede, o que significa que você consegue acessar se seu localhost estiver conectado a internet.

O problema de erro 500 é devido ao captcha.

Provavelmente você está usando o WAMP ou o LAMP no seu computador. Ele tem alguns problemas de compatibilidade. Recomendo usar o XAMP que funciona perfeitamente neste caso.
