### ISSUE TITLE
Erro de fuso horário no histórico do artigo

### ISSUE THREAD

**Issue by 77tnt** [KoreaComK/visao-libertaria-site#111]
Na tela https://ancap.su/colaboradores/artigos/detalhe/xxx, embaixo, tem "Histórico do artigo".
Os horários estão no fuso horário errado, parece ser 3 horas pra frente.

**Comment by KoreaComK** [comment]
A configuração do servidor estava correta, contudo, o que estava com a configuração errada era o GMT do banco de dados (local no qual os dados de data são pegos por padrão). Foi alterada a configuração usando o `SET GLOBAL time_zone = '-3:00';
Haverá um hiato nas próximas 3 horas e o histórico do site até este momento ficará com 3 horas adiantado, contudo o problema foi sanado.
