### ISSUE TITLE
Limite de caracteres do campo gancho

### ISSUE THREAD

**Issue by 77tnt** [KoreaComK/visao-libertaria-site#112]
Na tela "Escrever Artigo", https://ancap.su/colaboradores/artigos/cadastrar, tem o campo Gancho (Texto curto antes da vinheta. Máx. 100 palavras).
Ao salvar um texto com menos de 100 palavras, aparece uma mensagem de limite de 255 caracteres. Na prática o limite de 255 vem antes, difícil 100 palavras com menos de 255 chars.
Talvez aumentar o limite de caracteres, ou colocar na tela o limite de 255 caracteres no lugar de 100 palavras.

**Comment by KoreaComK** [comment]
Vou alterar para colocar 255 caracteres.
Feito em 3bb005e7e4c8ad2a3e2a40e5b84fc829b8e42318 .
