### ISSUE TITLE
Troca do tema para o AdminLTE visando melhor organização

### ISSUE THREAD

**Issue by Brunin12** [KoreaComK/visao-libertaria-site#149]
**Olá, desenvolvedores!**

Sou um desenvolvedor full stack com ampla experiência em projetos reais, utilizando CodeIgniter 3 e 4. Tenho acompanhado o projeto do site Visão Libertária do Ancapsu e admiro muito o trabalho que vocês têm feito. Gostaria de contribuir para o site, trazendo melhorias em termos de eficiência e organização.

Minha proposta é implementar um sistema de templates que permite o carregamento de conteúdo dinâmico de maneira mais eficiente, com a possibilidade de passar dados de forma otimizada entre as páginas. Além disso, essa abordagem traria um aspecto visual mais moderno e organizado.

### Minhas ideias principais:
- **Integrar o template [AdminLTE](https://github.com/ColorlibHQ/AdminLTE/tree/v3)** para melhorar o design e usabilidade.
- **Adicionar o [SweetAlert](https://sweetalert2.github.io/)** para implementar notificações e toasts mais elegantes e interativos.

Fico à disposição para discutirmos essas sugestões e como posso ajudar na implementação!

**Comment by KoreaComK** [comment]
@Brunin12 verificando as ideias informadas, percebi que elas utilizam o bootstrap 4 e não o 5.3, o mais atualizado, que utilizamos no projeto. O Sweetalert pode ser utilizado nas modais, caso seja de fácil implementação. Se você quiser, pode fazer um fork do projeto e criar uma branch nova, submetendo via PR as atualizações com o Sweetalert. Caso nos apeteça, podemos adicionar as alterações na versão atual do site.
Irei fechar essa issue como not planned, mas sinta-se a vontade em submeter o seu PR.
