### ISSUE TITLE
[bug] Ver Pagamentos

### ISSUE THREAD

**Issue by cronosk345** [KoreaComK/visao-libertaria-site#18]
Olá, parabéns pelo trabalho...

Acredito ter um erro no link **Ver Pagamentos** no perfil do colaborador.

Aparecem dados pra mim...  Ou está listando dados indevidos ou fake....

Segue imagem:
![image](https://github.com/KoreaComK/visao-libertaria-site/assets/146398230/8e53143a-704c-4dc7-9717-1ccc3bdf569c)

**Comment by KoreaComK** [comment]
São dados fakes, vou retirar essas informações para não causar dúvidas.

**Comment by cronosk345** [comment]
Imaginei.... :-)

**Comment by KoreaComK** [comment]
Ocultado a parte do histórico total do usuário. Ainda não desenvolvido.
8a167b7e637bc72442e395162aeb85f392287f8a
