### ISSUE TITLE
Outros sites

### ISSUE THREAD

**Issue by 77tnt** [KoreaComK/visao-libertaria-site#19]
Não sei como é a ideia agora para os sites do safesrc.com , wrevolving.com , opinionfreemarket.com , tomatenamao.com e mais algum que não lembro agora, mas deixo minha sugestão.

Manter o mesmo site para todos, mesmo banco de dados, mesmos logins de usuários, como era antigamente.
Cada site ter uma "casca" diferente, muda as imagens de logo, fundo, favicon, mas o back end é o mesmo, o front end muda minimamente (pra evitar retrabalho), só mudaria uma pasta de onde pega as imagens ou algo do tipo.
Ao sugerir uma pauta, marcar com uma "tag" cada pauta automaticamente, pelo site q o usuário veio. Por exemplo, se entrei no site ancap.su e sugeri uma pauta, ela fica marcada com "ANCAPSU"; se entrei pelo safesrc.com e sugeri, ela fica marcada com "safesrc".
Com possibilidade do Peter ao ler a pauta, mudar a tag, se for muito pesado pro "ANCAPSU" pode mudar para o "Opinion Free Market"; se sugeriram pelo ancapsubot, vem automatico como "ANCAPSU", mas pode mudar pro "safesrc" se for o caso.

**Comment by KoreaComK** [comment]
Feito parcialmente em bd50cb59bd28a7629e1c1aacbf238d370beb26df .

**Comment by KoreaComK** [comment]
Finalizado em fb28e56ec71acd9882238ad6378ec5978b171f02 .
