### ISSUE TITLE
Responsividade para mobile e outros

### ISSUE THREAD

**Issue by darlanhms** [KoreaComK/visao-libertaria-site#25]
Seria interessante um layout mais amigável para mobile, como visto na foto, ele não está redimencionando
Um começo seria adicionar um `<meta name="viewport" content="width=device-width, initial-scale=1.0">` nos html's das telas

![image](https://github.com/KoreaComK/visao-libertaria-site/assets/50335402/8d935c9a-5716-4373-9e1d-ef3a6d8c32aa)

**Comment by KoreaComK** [comment]
3ea6216d407b2f58562cabcbf66f9df6d379cfaa
