### ISSUE TITLE
Como contribuir

### ISSUE THREAD

**Issue by alande-amorim** [KoreaComK/visao-libertaria-site#26]
Seria interessante adicionar instruções de como contribuir para o projeto.

**Comment by KoreaComK** [comment]
Deixei o README com o passo a passo pra quem quiser baixar a versão do site local.

A contribuição pode ser feita corrigindo ou desenvolvendo algo que já tenha uma issue aberta, ou abrindo uma issue explicando o que gostaria de contribuir, e elencando a issue no PR, posteriormente.
