### ISSUE TITLE
Link de notícia abrir em outra aba

### ISSUE THREAD

**Issue by 77tnt** [KoreaComK/visao-libertaria-site#28]
Na tela "Leia a pauta", tem os campos "Link da Notícia" e "Link da Imagem" já cadastrados e bloqueados para edição. Proponho ao clicar neles, abrir em outra aba a notícia ou a imagem, com
`<a href="xxx" target="_blank">...</a>`

**Comment by KoreaComK** [comment]
Feito em ae32b70ffb0ea0f530a802acd76acaf08d25958a
