### ISSUE TITLE
Ajustar diagramação para celular

### ISSUE THREAD

**Issue by 77tnt** [KoreaComK/visao-libertaria-site#29]
O `<meta name="viewport" content="width=device-width, initial-scale=1.0">` já melhorou bem o site para celular, mas ainda poderia ter alguns ajustes de diagramação.

- A imagen no banner superior fica repedida, poderia a altura ser em função da largura do dispositivo.
- Os campos em "Sugira uma pauta" ficam pequenos, poderiam ter uma margem menor (também deixar em função da largura).
- A tela "Pautas sugeridas" não cabe na largura da tela está com barra de rolagem horizontal. Deve resolver se colocar as imagens em cima do texto, e não lado-a-lado como no desktop.

**Comment by KoreaComK** [comment]
10c5bf1484e2fb1cca3f8f46ce6b084c56bd6076
cdb02312540084da667f7e4f7c82d30fc96d1188
Corrigido.

**Comment by 77tnt** [comment]
Agora na versão para desktop, o banner de cima ficou cortado

**Comment by 77tnt** [comment]
ficou melhor se mudar para `height: 16.4vw`

`<div class="container-fluid" style="background-image:url(https://yt3.googleusercontent.com/qd_fOR_7fiOlxePKpWniaJSMla9Bv1jRV0wxufCxhVWHJ657Bzmh3yaK1PTi9BydS-2wTnlGCg=w1707-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj); height: 16.4vw; background-size: 100%;">`
