### ISSUE TITLE
Campo APELIDO não aceita acentuação.

### ISSUE THREAD

**Issue by insane-tsunami** [KoreaComK/visao-libertaria-site#33]
![image](https://github.com/KoreaComK/visao-libertaria-site/assets/2780113/d191f2b7-7d9c-42cf-a505-7de0859cf472)

**Comment by KoreaComK** [comment]
Atualizado e52bc73fcb4a4635cdd7a5be3212725bc357d410 .
O erro agora informa que não é permitido que o campo tenha acentuação.
