### ISSUE TITLE
Ajustar altura do banner

### ISSUE THREAD

**Issue by 77tnt** [KoreaComK/visao-libertaria-site#34]
Abrindo outra issue, imagino q não viu o comentário numa issue fechada

              ficou melhor se mudar para `height: 16.5vw`

`<div class="container-fluid" style="background-image:url(https://yt3.googleusercontent.com/qd_fOR_7fiOlxePKpWniaJSMla9Bv1jRV0wxufCxhVWHJ657Bzmh3yaK1PTi9BydS-2wTnlGCg=w1707-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj); height: 16.5vw; background-size: 100%;">`

_Originally posted by @77tnt in https://github.com/KoreaComK/visao-libertaria-site/issues/29#issuecomment-1751729812_

**Comment by KoreaComK** [comment]
Feito 20f5bb53e2296efac496b409013f7be6bad92905
