### ISSUE TITLE
Adicionar limite de notícias sugeridas por pessoas

### ISSUE THREAD

**Issue by KoreaComK** [KoreaComK/visao-libertaria-site#38]
5 por dia
20 por semana

**Comment by 77tnt** [comment]
Vai voltar o sistema de pontuação de pautador?
Uma coisa que a gente reclamava no site antigo era ter esse limite baixo mesmo pra quem tinha nota alta...

**Comment by KoreaComK** [comment]
A pontuação para pautas não está desenvolvida.
Entretanto, os limites serão configurados via administração. Esse é o limite informado pelo Peter que deverá ser padrão a priori.

**Comment by KoreaComK** [comment]
Feito em 7ccc143954bb196c0ba43335e62bf1135ba17676.
