### ISSUE TITLE
Retirar limite de tamanho de senha

### ISSUE THREAD

**Issue by KoreaComK** [KoreaComK/visao-libertaria-site#39]

**Comment by 77tnt** [comment]
Se realmente querem subir a bíblia como senha, vai bater no limite de POST do servidor

**Comment by KoreaComK** [comment]
O POST está com 50MB. Vou aumentar o limite para algo inimaginável para não ter problema.

**Comment by KoreaComK** [comment]
Limite aumentado para 5.000 caracteres. 77a49097c2ee02d9719bc6dbeab1dc180a4d017c
