### ISSUE TITLE
'Esqueci minha senha' não está funcionando

### ISSUE THREAD

**Issue by will-peixoto** [KoreaComK/visao-libertaria-site#40]
A funcionalidade de recuperação(ou redefinição) de senha não está funcionando.
Após colocar o e-mail e realizar o captcha nenhum e-email é enviado para minha conta e nenhuma mensagem é exibida na tela relatando o sucesso ou erro da operação.

(Testado no Chrome 117.0.5938.149)

**Comment by KoreaComK** [comment]
![image](https://github.com/KoreaComK/visao-libertaria-site/assets/86001769/72295408-2a0c-4312-a910-7943473fde67)

Aqui está funcionando corretamente, testando no Chrome quanto no Firefox.
O tempo da requisição demora cerca de 10 segundos.
Tente novamente, utilizando o Ctrl + F5 para limpar a cache ou abra uma página anônima.

Outro ponto é que o captcha só pode ser enviado uma única vez. Se colocou o e-mail errado e enviou, precisa atualizar a página e colocar o e-mail correto e realizar a verificação do captcha novamente.

Se mesmo assim não conseguir:
Atualize a página, aperte F12, navegue na aba escrita "Network" ou "Rede". Digite o seu e-mail no campo de e-mail e realize a verificação do captcha. Depois clique em "Enviar". Ao fazer isso, aparecerá uma linha nesta aba com o arquivo de nome "esqueci". Verifique se o resultado dele é 200. Se for, o erro está no seu e-mail. Se o erro for 500, me informe o e-mail ou o seu apelido no site, para verificar o que pode estar acontecendo.

**Comment by 77tnt** [comment]
Testei aqui e funcionou, o e-mail chegou rápido.

**Comment by KoreaComK** [comment]
Como não foi apontado nenhuma nova atualização sobre o assunto, estou fechando este chamado.
