### ISSUE TITLE
Criar gerenciamento de páginas estáticas do site

### ISSUE THREAD

**Issue by KoreaComK** [KoreaComK/visao-libertaria-site#54]

**Comment by josuecintra** [comment]
Imagino que nessa issue possa-se incluir acertar os links para as páginas ainda sem links em dois lugares:

1. em "Quick links" no rodapé
2. em "Informações úteis" no perfil das pessoas

Vou incluir aqui, também, a sugestão de abrir o link KoreacomK para este repositório em nova tela.

Se você preferir, pode desmembrar em outras issues conforme sua programação.

Ah, valeu pela implementação da lista de sugestões com sinalização do que foi aproveitado.... Só não sei se é interessante colocar uma cx de texto para justificar o pq a sugestão não foi aceita, pois geraria um montão de trabalho (Não repare ter embutido este parágrafo aqui, pois não quis gerar outra thread.... uma hora sei que vc esbarrará com este agradecimento! ;o)

Parabéns pelo seu trabalho.

**Comment by KoreaComK** [comment]
Adicionado na nova versão do site.
