### ISSUE TITLE
Erro ao recuperar a senha

### ISSUE THREAD

**Issue by SatsCzar** [KoreaComK/visao-libertaria-site#70]
Quando tento recuperar minha senha, recebo um 500 sem nenhuma informação adicional.
![Screenshot_4263](https://github.com/KoreaComK/visao-libertaria-site/assets/104809510/af4bc0f2-9572-4095-84da-78c0c6868b65)

**Comment by 77tnt** [comment]
Não consegui reproduzir, testei aqui e funcionou

**Comment by 77tnt** [comment]
@KoreaComK 
talvez não seja boa prática mostrar "O e-mail não já está cadastrado em nossa base de dados.", seja melhor mostrar a mesma mensagem se a conta existe ou não...

**Comment by SatsCzar** [comment]
@77tnt eu responderia com um 200 e exibiria uma mensagem `Caso você esteja cadastrado, um link de redefinição foi enviado para seu email`, desta forma, não vazando quem tem e quem não tem conta.

**Comment by SatsCzar** [comment]
Se a questão era de não ter conta, então foi falha minha, pois eu tinha certeza que meu cadastro tinha sido efetuado com sucesso, obrigado guys !

**Comment by SatsCzar** [comment]
Reabrindo, eu já estou cadastrado.
![Screenshot_4266](https://github.com/KoreaComK/visao-libertaria-site/assets/104809510/7c6077e2-929d-44b5-a3ea-9fc474bf6da5)

**Comment by 77tnt** [comment]
Testei com um email cadastrado e um não cadastrado, nos dois casos retornou 200 com uma tela
Testei com esse e-mail bolsonitro_bitcoiner@protonmail.com e voltou erro 500, é alguma coisa com essa conta. Talvez conta tá esperando confirmação, ou foi cadastrada e dá algum erro na hora de enviar o e-mail...

**Comment by SatsCzar** [comment]
> Testei com um email cadastrado e um não cadastrado, nos dois casos retornou 200 com uma tela Testei com esse e-mail [bolsonitro_bitcoiner@protonmail.com](mailto:bolsonitro_bitcoiner@protonmail.com) e voltou erro 500, é alguma coisa com essa conta. Talvez conta tá esperando confirmação, ou foi cadastrada e dá algum erro na hora de enviar o e-mail...

Pois é rapaz deve ser alguma coisa na conta, nunca consegui logar nela.

**Comment by 77tnt** [comment]
1. Criei uma conta nova
2. Não confirmei
3. Fui no esqueci minha senha, coloquei o email
4. Retornou 200, aviso normal "Foi enviado um e-mail para redefinição de senha. Clique no link para ter acesso a área redefinição de senha."
5. Email que chegou foi de redefinição de senha, talvez nesse caso devesse reenviar o de confirmação

Mas não deu 500... então o caso acima deve ser específico do email bolsonitro_bitcoiner@protonmail.com , @KoreaComK se puder ver nos logs

**Comment by KoreaComK** [comment]
@SatsCzar verifiquei que existia uma função do Code Igniter que colocava um ! (exclamação) na frente do _ (underline).
Fiz a alteração no código e forcei ele mandar novamente o link para você, verifique se agora ele foi.
@77tnt  obrigado pela ajuda.
@SatsCzar verifique se foi resolvido. Em caso positivo, peço para fechar a issue.

**Comment by SatsCzar** [comment]
Funcionou hehehe
