### ISSUE TITLE
Sugestão - Permitir criação de contas utilizando nostr

### ISSUE THREAD

**Issue by guilhermegps** [KoreaComK/visao-libertaria-site#79]
Permitir que durante o cadastro você consiga utilizar o nostr ao invés de um e-mail.

Duas sugestões possíveis:

Primeira (preferível) - Autenticação utilizando a chave do nostr. Carregando automaticamente o nome e etc, dispensando a criação de conta em si.

Segunda - Permitir usar o nostr apenas como 2FA, substituindo o e-mail. Poderia solicitar a npub ou o [NIP-05](https://github.com/nostr-protocol/nips/blob/master/05.md) e enviar uma mensagem privada (usando o [NIP-04](https://github.com/nostr-protocol/nips/blob/master/04.md))

**Comment by guilhermegps** [comment]
Existe  [esta](https://github.com/swentel/nostr-php) framework que pode ajudar.

**Comment by guilhermecaixeta** [comment]
Seria uma boa mesmo, outro ponto é integrar a hablanews os artigos assim para alcançar quem está no nostr mas não segue diretamente o site de vocês.

**Comment by KoreaComK** [comment]
Infelizmente não iremos implementar cadastros de outras fontes que não sejam diretamente do site, por motivos de privacidade, segurança e limitação de informações em caso de vazamento de dados.
