### ISSUE TITLE
Aumentar o número de linhas do textarea para enviar notícias na versão mobile

### ISSUE THREAD

**Issue by josuecintra** [KoreaComK/visao-libertaria-site#80]
Olá KoreaComK!

Parabéns pelo seu trabalho tanto aqui com a nova versão do site, qt pelas suas atuações nos canais.

Cara, podes colocar uma regra de css para aumentar o número de linhas do textarea para enviar notícias na versão mobile?

2 linhas não dá uma boa experiência de uso, principalmente quando vamos revisar o texto digitado para fazer a submissão.

**Comment by KoreaComK** [comment]
Vou verificar se consigo colocar essa melhoria. Assim que ela for adicionada, fecho essa issue informando que foi implementada.

**Comment by KoreaComK** [comment]
Feito em 028da2ade9198768cd029c4b8b961639faa39883 .
