### ISSUE TITLE
Sugestão avaliada

### ISSUE THREAD

**Issue by josuecintra** [KoreaComK/visao-libertaria-site#81]
Criação de checkbox para o Peter ou colaboradores marcar uma sugestão como vista.

Isso é interessante para os recomendadores ao menos ver que alguma de suas sugestões foi considerada.

Imagino que não seja tudo o que conseguem ler, mas já é uma sinalização de não estarmos no vácuo

**Comment by 77tnt** [comment]
+1

site antigo tinha uma marcação se a notícia sugerida foi usada em algum vídeo, acho legal ter no sistema novo

**Comment by KoreaComK** [comment]
Estou pensando em enviar um e-mail para as pessoas informando quais pautas foram utilizadas e também quais pautas da pessoa ele utilizou.

**Comment by 77tnt** [comment]
e-mail acho que só incomodaria... talvez só uma tela com as pautas utilizadas do usuário

**Comment by josuecintra** [comment]
Talvez, na lista de pautas sugeridas de cada autor, colocar um ícone de
olho fechado na submissão, mudar para aberto para o que ele (ou os
colaboradores) abriram/leram e um de checked para o que foi usado nos
vídeos.

Os lidos podem ser marcados de maneira transparente baseando na abertura da
pauta por determinadas pessoas... já os checkeds dependeria de uma ação
deles em marcar o que usaram.... Talvez a criação de uma "cesta" de compras
para agrupar os artigos desejados para determinada cesta.


Em qui., 21 de dez. de 2023 18:41, T. N. T. ***@***.***>
escreveu:

**Comment by KoreaComK** [comment]
Criado uma listagem no perfil do usuário mostrando todas as pautas que foram pegas pelo Peter para virar vídeo, mostrando um link para a pauta e a data na qual ela foi incluída no fechamento das pautas. a098f2f8b829476c9fcdad73033b0486156cde18
