### ISSUE TITLE
Notícia recente detectada como antiga

### ISSUE THREAD

**Issue by RafaelEstevamReis** [KoreaComK/visao-libertaria-site#87]
Ao sugerir a notícia `https://oantagonista.com.br/brasil/gilmar-responsabiliza-bolsonaro-por-8-de-janeiro/`, o site detectou como notícia antiga (+5d)

A tentativa foi no dia 06/Jan, a notícia era do dia 05/Jan, menos de 24 horas

![image](https://github.com/KoreaComK/visao-libertaria-site/assets/9899419/0842f596-830e-41eb-8495-f9cb88fae6a3)
![image](https://github.com/KoreaComK/visao-libertaria-site/assets/9899419/2bcd1512-90a4-4ea6-a4c1-97565fc7b52f)

**Comment by RafaelEstevamReis** [comment]
Em conversa no discord, foi localizado que o trecho que o site utiliza para detectar a data está mal-formtado
![image](https://github.com/KoreaComK/visao-libertaria-site/assets/9899419/9f870eed-632d-424a-8fc4-fcf5f29485dc)

Os metas parecem corretos, porém hoje não são utilizados
`<meta property="article:published_time" content="2024-01-05T22:11:41+00:00" />`
O `yoast-schema-graph` também está com a data correta: `"datePublished":"2024-01-05T22:11:41+00:00"`

E a tag no próprio artigo também esta bem formatada (embora sem o T)
`<time datetime="2024-01-05 19:11:41">05/01/24 19:11</time>`

**Comment by KoreaComK** [comment]
Atualizado a pesquisa das informações em 03ab85be2222be7157b11895c6ba181cbae1a4ed .
