### ISSUE TITLE
Integrar site com bot do twitter

### ISSUE THREAD

**Issue by 77tnt** [KoreaComK/visao-libertaria-site#88]
- Criar no site um cadastro opcional de @ do twitter para cada usuário
- Ao marcar o bot, enviar o link do tweet e usuario para o site
- O site verificar se o usuário é cadastrado, se estourou o limite de pautas, se foi bloqueado, se a pauta já foi cadastrada
- Site responder ao bot e bot postar como resposta ao tweet: "Pauta cadastrada", "Usuário precisa se cadastrar no site", etc
- Verificar se há um limite de posts de reposta do bot, em alguns casos só não responder nada (especialmente usuário bloqueado, ou se já avisou várias vezes para fazer o cadastro no site).

Minha ideia de ter uma opção de bloquear usuário é por que muita gente marca o bot só pra encher o saco. Observei que vinha muito lixo quando as pautas do bot caiam no discord.

**Comment by KoreaComK** [comment]
Feito em 5a6281befa9776fbac2552447ef796f73162d34e .
