### ISSUE TITLE
Adicionar tooltip falando o motivo pelo qual o botão está bloqueado.

### ISSUE THREAD

**Issue by KoreaComK** [KoreaComK/visao-libertaria-site#9]

**Comment by 77tnt** [comment]
eu faria uma faixa vermelha perto do botão
dai coloca texto como "texto precisa ter entre x e y palavras", "precisa ter xyz", etc
o mesmo script q libera/bloqueia o botão, se cumprir a regra, oculta o texto do aviso, e se não tem nenhum texto, oculta a faixa vermelha

**Comment by KoreaComK** [comment]
Adicionado 58a69e36b468020930b4e99ab728b396baf1ce49
