### ISSUE TITLE
Criar caminho para usuário apagar pauta sugerida

### ISSUE THREAD

**Issue by 77tnt** [KoreaComK/visao-libertaria-site#92]
Não há caminho para apagar link enviado errado, nem é possível editar o link depois de enviado.
Poderia ter um caminho na tela de pauta sugerida, só para o próprio usuário que enviou. Talvez com um limite de tempo.

**Comment by KoreaComK** [comment]
Feito em c62a0ffbb3dee99f81e481c0d051b7b8dc4a8331 .
