### ISSUE TITLE
A listagem de Pautas Sugeridas no Perfil não está ordenado

### ISSUE THREAD

**Issue by RafaelEstevamReis** [KoreaComK/visao-libertaria-site#93]
Em conversa, KoreacomK informou que a listagem está sem ordenação e solicitou abertura de Issue

Tela: `Perfil` > `Listar pautas usadas em vídeos`

Atualmente: `ORDER BY Freestyle DESC`

Sugestão: `ORDER BY DataFechamento DESC`

**Comment by KoreaComK** [comment]
Resolvido em 9f0379ac483151cd34ed94cfb52ce5ebed9c100c .
