### ISSUE TITLE
Após salvar usuário do twitter não consigo mais alterar o perfil

### ISSUE THREAD

**Issue by hkupty** [KoreaComK/visao-libertaria-site#94]
ref:  #88

Adicionei meu usuário do twitter agora e percebi que não tinha colocado minha carteira de BTC. Quando tentei adicionar, a mensage seguinte foi mostrada sem persistir a alteração que eu solicitei.
![image](https://github.com/KoreaComK/visao-libertaria-site/assets/2695819/aa3e6dd6-93be-4ff0-bd81-b7f361a0ac1c)

**Comment by KoreaComK** [comment]
Resolvido em #95 .
