### ISSUE TITLE
Editar/criar usuário sem usuário do Twitter/X

### ISSUE THREAD

**Issue by 77tnt** [KoreaComK/visao-libertaria-site#95]
- Edite o perfil de usuário
- Deixe o campo "Usuário no X (antigo Twitter) em branco
- Não salva, retorna erro "O @ já está cadastrado em nossa base de dados."

Deveria permitir campo em branco, não checar duplicidade.

**Comment by KoreaComK** [comment]
Feito em 5b4855c3aa4f848a6ae6a338fa5434e758b3e989
