### ISSUE TITLE
Criar configuração Docker para o projeto

### ISSUE THREAD

**Issue by diegosurita** [KoreaComK/visao-libertaria-site#96]
Olá, meu nome é Diego. Acompanho o conteúdo dos canais do Peter e gostaria de contribuir com o projeto.

Como minha primeira contribuição eu pensei em fazer a configuração de Docker no projeto, pra ficar mais fácil o setup do ambiente de dev para outros devs que quiserem contribuir também.
Dito isso, eu tenho algumas dúvidas para a configuração do docker compose.

Qual banco de dados é usado? (se tiver uma versão específica, me diga também por favor)
Qual versão do PHP o projeto está rodando em produção?
O servidor web está rodando o projeto? Apache ou Nginx?
Qual distro do linux que o projeto está rodando?

**Comment by KoreaComK** [comment]
Segue as informações necessárias para executar o projeto:

Banco de dados: MariaDB 10.6.9^
PHP: 8.0^
CodeIgniter: 4.3.7^ (Recomendado o 4.3.7 por facilidade de configuração)
Servidor: Apache 2.4.50^
Composer: 2.6.6
